### ISSUE TITLE
It is recommended that you can easily restore the derived key and specify the GPG-related path.

### ISSUE THREAD

**Issue by wy16W2pIilK1xgqN** [svareille/OnlyKey-gpg-agent#3]
The GPG must load the corresponding public key of the Derived key in order to work with the ok-gpg-agent, if the public key is lost, everything is unusable.
It is recommended that you write the parameters to [[keyinfo]] when the ok-gen-key generates a key, so that you can quickly recover it later.

Now the software only looks for GPG.exe in the PATH, which is inconvenient in some cases, such as when working on USB, you want to add a parameter specifying the GPG-related path.

At last
Thank you for the software that made my OnlyKey finally have something to do. Thank you.🎉😉

**Comment by svareille** [comment]
Hi! Thanks for your interest!

I will follow your suggestions, these are great additions.

**Comment by svareille** [comment]
Done in [v1.1.0](https://github.com/svareille/OnlyKey-gpg-agent/releases/tag/v1.1.0)
